---
functional:
  - Возможность соревнования двух игроков друг с другом в реальном времени, решая задачи и смотря код друг друга
  - Возможность играть с ботом для тренировки
  - Возможность пригласить друга по ссылке и сыграть вместе
  - Система рейтингов, с последующим отслеживанием достижений пользователя
  - Регистрация и авторизация в целом, через учетные записи пользователей
non-functional:
  - Высокая скорость загрузки страниц сайта
  - Защита данных пользователей и безопасности само приложение
  - Интерфейс приложения адаптирован под мобильные устройства
  - Совместимость с последними версиями популярных браузеров
  - Масштабируемая система, которая бы смогла обрабатывать 1000 одновременных пользователей
implicit:
  - Интуитивно понятный интерфейс для пользователей разного уровня подготовки
  - Простота развертывания и поддержки проекта из-за доступности документации
  - Автоматизированные и ручные тесты для проверки работоспособности системы
  - Возможность дальнейшей наработки идеи и расширения конструкта функций по инициативе сообщества
