---
functional:
  - Возможность соревнования двух игроков друг с другом в реальном времени, решая задачи и смотря код друг друга
  - Возможность играть с ботом для тренировки
  - Возможность пригласить друга по ссылке и сыграть вместе
  - Система рейтингов, с последующим отслеживанием достижений пользователя
  - Регистрация и авторизация в целом, через учетные записи пользователей
  - Пользователю должна быть предоставлена возможность восстановления пароля
  - Предоставлена возможность начать простую игру без создания учетной записи
  - В игре пользователю предоставлена возможность писать в чат
  - Пользователю доступен подробный рейтинг игроков, турниров и история игр
  - Функциональность создания турниров доступна пользователю
  - Пользователь может фильтровать рейтинг игроков и осуществлять поиск по имени
  - Пользователь может следить за активностью других пользователей
  - Пользователь может просматривать детали задач и создавать новые
  - Во время игры пользователь видит окна со своим кодом и кодом соперника
  - В игровом процессе пользователь может сдаться, обнулить код или запросить проверку решения
non-functional:
  - Высокая скорость загрузки страниц сайта
  - Защита данных пользователей и безопасности самого сайта
  - Интерфейс приложения адаптирован под мобильные устройства
  - Совместимость с последними версиями популярных браузеров
  - Масштабируемая система, которая бы смогла обрабатывать 1000 одновременных пользователей
implicit:
  - Интуитивно понятный интерфейс для пользователей разного уровня подготовки
  - Простота развертывания и поддержки проекта из-за доступности документации
  - Автоматизированные и ручные тесты для проверки работоспособности системы
  - Возможность дальнейшей наработки идеи и расширения конструкта функций по инициативе сообщества
